### ISSUE TITLE
some mistakes in portuguese brazil and lack of translation

### ISSUE THREAD

**Issue by LucasMonFC** [RicardoGuariento/MIUI-XML-14-BRAZILIAN#1]
I confirm that Portuguese (Brazil) lacks some translations like below (previous annex):

Aceder => Permitir
Ficheiro=> Pasta
Info. do app => Info. do aplicativo
Edit icon => Editar ícone
Detailed info and specs => Informações detalhadas e especificações
Tap an app on the sidebar to open it in a floating
window => Toque em um aplicativo na barra lateral para abri-lo em janela flutuante
Computer => Computador
Continue tasks in the same app on your tablet => Continue tarefas no mesmo aplicativo em seu tablet
Connect automatically => Conectar automaticamente
Connect to other tablets associated with
your Xiaomi Account automatically => Conecte-se a outros tablets associados a
sua conta Xiaomi automaticamente
Connected device => Dispositivo conectado
Icon size => Tamanho do ícone
Available icons => Ícones disponíveis
Default => Padrão
More => Mais

**Comment by DiorgenesS** [comment]
Qual aplicativo ocorre isso?

**Comment by LucasMonFC** [comment]
aplicativo de configuração e system.ui do sistema maiorias das traduções esta portugues de portugal
