### ISSUE TITLE
Selecionar o modo de bateria nas configurações de apps

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/MIUI-XML-14-BRAZILIAN#10]
![Screenshot_2023-08-22-16-42-09-686_com.miui.powerkeeper.jpg](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/bb6e0d06-a861-4d92-98c6-8aa27a9c231d)

Uma das opções de modo de bateria nas configurações de apps individuais não está com a descrição traduzida.

**Comment by DiorgenesS** [comment]
Ola eu verifiquei e essa linha ja esta traduzida, por algum motivo nao foi puxada.
segue linha original no repo: [EN-US]( https://github.com/ingbrzy/Xiaomi.eu-MIUIv14-XML-Compare/blob/master/diting/PowerKeeper.apk/res/values/strings.xml#L129C76-L129C76)
linha ja traduzida: [PT-BR](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/blob/main/Brazilian-Portuguese/main/PowerKeeper.apk/res/values-pt-rBR/strings.xml#L68).

Anyway coloquei duas "" para ver se agora eles atualizam ->https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/commit/0284f0a67f494418ab30334598400d4df5d54829

O meu esta traduzido, limpa os dados do app Powerkeep
![Screenshot_2023-08-22-20-10-18-993_com miui powerkeeper](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/16513009/acb816aa-8f2c-40d5-8f5d-e7e5ebc24417)

**Comment by EduardoRGCM** [comment]
> Ola eu verifiquei e essa linha ja esta traduzida, por algum motivo nao foi puxada.
> segue linha original no repo: [EN-US]( https://github.com/ingbrzy/Xiaomi.eu-MIUIv14-XML-Compare/blob/master/diting/PowerKeeper.apk/res/values/strings.xml#L129C76-L129C76)
> linha ja traduzida: [PT-BR](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/blob/main/Brazilian-Portuguese/main/PowerKeeper.apk/res/values-pt-rBR/strings.xml#L68).
> 
> Anyway coloquei duas "" para ver se agora eles atualizam ->https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/commit/0284f0a67f494418ab30334598400d4df5d54829
> 
> O meu esta traduzido, limpa os dados do app Powerkeep
> ![Screenshot_2023-08-22-20-10-18-993_com miui powerkeeper](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/16513009/acb816aa-8f2c-40d5-8f5d-e7e5ebc24417)
> 

Tentei limpar os dados, porém ainda assim continua em inglês.
Vou esperar a próxima build pra ver se vai corrigir.
