### ISSUE TITLE
Informações sobre o encerramento do MiCloud na Galeria

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/MIUI-XML-14-BRAZILIAN#11]
![Screenshot_2023-08-25-09-25-23-165_com.miui.gallery.jpg](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/3248f9a8-ecc4-4c77-8053-76a9e77da49a)

Esse aviso de encerramento do Mi Cloud ao abrir a galera não está traduzido.

**Comment by DiorgenesS** [comment]
@EduardoRGCM foi traduzido no commit relacionado ao Google Fotos ->https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/commit/035ee18bc1455e1b39d71dcbd36b3209a3a269ad#diff-fbd1feb830dcd34ec6002d4f97a5631e97a40b4299b156ad347a796def438dfcR3162
