### ISSUE TITLE
Dicas de Janelas flutuantes

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/MIUI-XML-14-BRAZILIAN#12]
As dicas relacionadas às janelas flutuantes não estão traduzidas.

![IMG_20230825_134752.jpg](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/8df8e628-c8da-4a4e-8aa2-764d5218642a)

![IMG_20230825_134853.jpg](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/ac06eb59-c97c-4d8f-a62b-719c994e2dc5)

![IMG_20230825_134809.jpg](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/afa17985-a5ca-4d89-9489-bd4297ac8068)

![IMG_20230825_134931.jpg](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/44e77fe6-b3df-490b-a0a4-41131891a682)

Não consegui tirar uma captura de tela de todas, já que aparecem apenas uma vez, mas tirei algumas.

**Comment by DiorgenesS** [comment]
@EduardoRGCM todos já estão traduzidos -> [linhas 181 a 193](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/blob/main/Brazilian-Portuguese/main/framework-ext-res.apk/res/values-pt-rBR/strings.xml#L193C32-L193C32) aguardar pela próxima atualização
