### ISSUE TITLE
As configurações de marca d'água / Câmera 

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/MIUI-XML-14-BRAZILIAN#13]
![Screenshot_2023-08-26-14-24-39-150_com.android.camera.jpg](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/5aa59ac0-71da-4cc5-a990-74d5b408690c)

Descrição de configurações de marca d'água no modo pro não estão traduzidas.

**Comment by DiorgenesS** [comment]
Traduzido -> [here](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/commit/231c01b8b3ec00a1a223762cd2316a983dfa269f#diff-7a520cbfc3047bf0337cbebb8ef42f24660426ad541c635bc76cfaa806e2e7e5R1921)
