### ISSUE TITLE
Sugestão de Tarefas Automáticas

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/MIUI-XML-14-BRAZILIAN#14]
![Screenshot_2023-08-27-16-36-33-329_com.miui.securitycenter.jpg](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/d12bcd8b-51c6-4fa9-bd9b-2aa60d48b65b)

Os títulos das sugestões de exemplos de tarefas Automáticas estão sem a tradução.

**Comment by DiorgenesS** [comment]
Já enfrentei esse problema, as linhas estão traduzidas, porém por algum motivo há a necessidade de limpar os dados do app segurança.
