### ISSUE TITLE
Modos de bateria

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/MIUI-XML-14-BRAZILIAN#15]
Mesmo após limpar dados e formatar o dispositivo após atualização com a tradução atualizada, ainda não aparece traduzido.

![IMG_20230902_213802.jpg](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/d55bc753-de18-4bbd-beb5-848ed26ac7ed)

**Comment by DiorgenesS** [comment]
Qual o seu dispositivo?

**Comment by EduardoRGCM** [comment]
> Qual o seu dispositivo?

Redmi Note 12 Pro 5G (Ruby)

**Comment by DiorgenesS** [comment]
Poderia disponibilizar o link de onde baixou a rom?
Pois procurei no site da xiaomi.eu que é pra onde essa tradução se destina, e não encontrei pro seu dispositivo

**Comment by EduardoRGCM** [comment]
> Poderia disponibilizar o link de onde baixou a rom?
> Pois procurei no site da xiaomi.eu que é pra onde essa tradução se destina, e não encontrei pro seu dispositivo 

Essa rom é disponibilizada mediante uma assinatura no Patreon, onde o desenvolvedor produz Roms para dispositivos Mediatek Dimensity.
Eu não estou autorizado a fornecer links de download, já que é um conteúdo pago, mas vou entrar em contato com o desenvolvedor e verificar se posso disponibilizar para que seja corrigido.

**Comment by DiorgenesS** [comment]
> > Poderia disponibilizar o link de onde baixou a rom?
> > Pois procurei no site da xiaomi.eu que é pra onde essa tradução se destina, e não encontrei pro seu dispositivo
> 
> Essa rom é disponibilizada mediante uma assinatura no Patreon, onde o desenvolvedor produz Roms para dispositivos Mediatek Dimensity. Eu não estou autorizado a fornecer links de download, já que é um conteúdo pago, mas vou entrar em contato com o desenvolvedor e verificar se posso disponibilizar para que seja corrigido.

Entendi, engraçado que ele pega string públicas e coloca em uma ROM para depois cobrar, fazer o que né, então é provável que ele não puxou as versão mais recente.

Infelizmente, erros de tradução você devera reportar ao desenvolvedor, já que ele cobra pela ROM, nada mais justo que ele corrigir.
Obg.

**Comment by EduardoRGCM** [comment]
> > > Poderia disponibilizar o link de onde baixou a rom?
> > > Pois procurei no site da xiaomi.eu que é pra onde essa tradução se destina, e não encontrei pro seu dispositivo
> > 
> > Essa rom é disponibilizada mediante uma assinatura no Patreon, onde o desenvolvedor produz Roms para dispositivos Mediatek Dimensity. Eu não estou autorizado a fornecer links de download, já que é um conteúdo pago, mas vou entrar em contato com o desenvolvedor e verificar se posso disponibilizar para que seja corrigido.
> 
> Entendi, engraçado que ele pega string públicas e coloca em uma ROM para depois cobrar, fazer o que né, então é provável que ele não puxou as versão mais recente.
> 
> Infelizmente, erros de tradução você devera reportar ao desenvolvedor, já que ele cobra pela ROM, nada mais justo que ele corrigir.
> Obg.

Todas as outras traduções que eu reportei, estão corrigidas nessa atualização que recebi hoje, acredito que ele deve ter sim usado o arquivo mais recente.
Vou deixar o link aqui pra caso você puder, dar uma olhada, mas o link de download é enviado por e-mail e não é disponibilizado no site.

https://www.patreon.com/xiaomieu

**Comment by DiorgenesS** [comment]
> > > > Poderia disponibilizar o link de onde baixou a rom?
> > > > Pois procurei no site da xiaomi.eu que é pra onde essa tradução se destina, e não encontrei pro seu dispositivo
> > > 
> > > 
> > > Essa rom é disponibilizada mediante uma assinatura no Patreon, onde o desenvolvedor produz Roms para dispositivos Mediatek Dimensity. Eu não estou autorizado a fornecer links de download, já que é um conteúdo pago, mas vou entrar em contato com o desenvolvedor e verificar se posso disponibilizar para que seja corrigido.
> > 
> > 
> > Entendi, engraçado que ele pega string públicas e coloca em uma ROM para depois cobrar, fazer o que né, então é provável que ele não puxou as versão mais recente.
> > Infelizmente, erros de tradução você devera reportar ao desenvolvedor, já que ele cobra pela ROM, nada mais justo que ele corrigir.
> > Obg.
> 
> Todas as outras traduções que eu reportei, estão corrigidas nessa atualização que recebi hoje, acredito que ele deve ter sim usado o arquivo mais recente. Vou deixar o link aqui pra caso você puder, dar uma olhada, mas o link de download é enviado por e-mail e não é disponibilizado no site.
> 
> https://www.patreon.com/xiaomieu

Eu olhei o link e realmente faz parte da xiaomi.eu, agora não sei pq não está traduzido no seu, as linhas referente a esse texto são apenas 2, e ambas estão traduzidas.
Adicione o PowerKeep.apk, vou verificar

**Comment by EduardoRGCM** [comment]
Fiz o upload no Gdrive, vou deixar o link.

https://drive.google.com/file/d/1wCqE81hqnaBlg2g5sx0WBl4MSiIeBg2j/view?usp=drive_link

**Comment by DiorgenesS** [comment]
> Fiz o upload no Gdrive, vou deixar o link.
> 
> https://drive.google.com/file/d/1wCqE81hqnaBlg2g5sx0WBl4MSiIeBg2j/view?usp=drive_link

Olhei e o seu a linha correspondente seria:
### "string name="config_restrict_function_description_new"
e essa linha no seu apk não esta inclusa no values-pt-rBR, porém no repo essa linha ja foi adicionada, [(veja aqui)](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/blob/main/Brazilian-Portuguese/main/PowerKeeper.apk/res/values-pt-rBR/strings.xml#L69C53-L69C53) tem que pedir aos desenvolvedores fazer o sync das traduções.

Então do lado da tradução está tudo certo, eles só precisam sincronizar.
