### ISSUE TITLE
Descrição da função "Casa inteligente"

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/MIUI-XML-14-BRAZILIAN#16]
![Screenshot_2023-09-02-23-22-08-155_com.android.settings.jpg](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/572da1fd-e318-4116-8066-59ce25741b83)

A descrição da função casa inteligente não está traduzida.

**Comment by DiorgenesS** [comment]
Traduzido
