### ISSUE TITLE
Widgets de relógio no App Vault

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/MIUI-XML-14-BRAZILIAN#17]
![IMG_20230905_181152.jpg](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/6fefd330-b9ef-4091-a67e-8192d5f8a932)

O texto não está traduzido

**Comment by EduardoRGCM** [comment]
> ![IMG_20230905_181152.jpg](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/6fefd330-b9ef-4091-a67e-8192d5f8a932)
> 
> O texto não está traduzido 

"Custom clocks" e o "Pals" que não circulei, mas estão logo abaixo.

**Comment by DiorgenesS** [comment]
Já está traduzido [here,](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/blob/main/Brazilian-Portuguese/extras/AppVault/strings/strings_pt_BR.xml#L13) porém é necessário que eles empurre a atualização do appvault para o servidor deles.

Então vou marcar como resolvido.
