### ISSUE TITLE
Erro de espaçamento nas marcas de localização 

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/MIUI-XML-14-BRAZILIAN#18]
![IMG_20230907_212215.jpg](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/ff0546ca-347e-4667-8f6c-1d8862b79b76)

Não se é algo da Miui ou é algo relacionado à tradução, mas está faltando um espaço ali em "Minas Gerais e Goiás"

**Comment by DiorgenesS** [comment]
Essa parte não é traduzivel, se mudar o idioma poderá observar que permanecerá igual.

**Comment by EduardoRGCM** [comment]
> Essa parte não é traduzivel, se mudar o idioma poderá observar que permanecerá igual.

Ah entendi, é bug da Miui mesmo então.
