### ISSUE TITLE
Aviso de Marca d'água na Galeria

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/MIUI-XML-14-BRAZILIAN#19]
![Screenshot_2023-09-08-10-02-02-972_com.miui.extraphoto.jpg](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/9bdd5173-8abb-42d5-bb84-3793a38ba992)

O aviso sobre a marca d'água não está traduzido.

**Comment by DiorgenesS** [comment]
https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/commit/63039344d109ccba72a5b1b2d88ffbf4cbc737d7#diff-37c211b918df5e80f8c6942babcfa362cfe0d686c1c00e434c0b52683b15fcdaR340
