### ISSUE TITLE
Data na Central de Notificações com inconsistencia

### ISSUE THREAD

**Issue by freecssSmash** [RicardoGuariento/MIUI-XML-14-BRAZILIAN#2]
Na Miui global o portugues Brasil já está corrigido a data na central, na .eu fica mostrando completo e atrapalha a consistencia de Layout, tanto que na parte de notificações o clima fica cortado, conforme prints. obs: o que está normal está no idioma portugues de Portugal
![Screenshot_2022-12-31-11-29-34-231_com google android apps photos](https://user-images.githubusercontent.com/62391901/210144069-68006f73-7ec6-4ae3-a0ce-c141db096611.jpg)
![Screenshot_2022-12-31-11-26-54-504_com android settings](https://user-images.githubusercontent.com/62391901/210144092-b71fb2bb-0553-4841-a1e0-be5a742f13be.jpg)
![Screenshot_2022-12-31-11-26-31-431_com miui home](https://user-images.githubusercontent.com/62391901/210144099-6008c393-0c6b-4856-b6ba-3fbd6d3e620d.jpg)

**Comment by pradovinicius** [comment]
Tive essas inconsistências no widget do clima tbm.. Mas a central de notificações minha ta ok!
