### ISSUE TITLE
Erro na grafia - Falta um acento

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/MIUI-XML-14-BRAZILIAN#20]
![IMG_20230916_123609.jpg](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/2c0be5bf-617c-4500-b1a4-c67daf936d6f)

Se trata apenas da falta de um acento na palavra "Dinâmica".

**Comment by DiorgenesS** [comment]
Done -> https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/commit/bd3b2ee89d58f8dec7ce47a0e81c922a41d4b3d3
