### ISSUE TITLE
Letras Iniciais / Dias de Folga / App Agenda

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/MIUI-XML-14-BRAZILIAN#21]
![Screenshot_2023-09-16-18-07-19-589_com.android.calendar-edit.png](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/f8db2b14-9fff-4711-8a2c-2326b4101bbb)

Notei que no aplicativo global, as letras correspondentes aos dias da semana não são também não são traduzidas, é uma característica do aplicativo?

**Comment by EduardoRGCM** [comment]
> ![Screenshot_2023-09-16-18-07-19-589_com.android.calendar-edit.png](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/f8db2b14-9fff-4711-8a2c-2326b4101bbb)
> 
> Notei que no aplicativo global, as letras correspondentes aos dias da semana não são também não são traduzidas, é uma característica do aplicativo?

Esse print é da Xiaomi.eu, eu apenas comparei ao aplicativo da Miui global em outro aparelho para saber se estava traduzido nele.

**Comment by DiorgenesS** [comment]
Não é traduzivel
