### ISSUE TITLE
Widgets do Assistente / App Vault

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/MIUI-XML-14-BRAZILIAN#22]
![Screenshot_2023-09-17-00-37-48-274_com.miui.personalassistant.jpg](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/c07ad729-bd6b-4758-9a8a-15ae2e2fd17a)

![Screenshot_2023-09-17-00-37-38-899_com.miui.personalassistant.jpg](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/cda3b33d-cb27-48fa-8b2c-b352b47e0698)

![Screenshot_2023-09-17-00-37-54-972_com.miui.personalassistant.jpg](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/7df621d8-d6a3-46bf-9795-58bd91ca5a34)

Alguns títulos e descrição de widgets não estão com a tradução.

Obs.: Não observei se antes da atualização estava traduzido, mas após atualizar notei que estão sem tradução.

**Comment by DiorgenesS** [comment]
Todos já estão traduzido aqui -> https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/blob/main/Brazilian-Portuguese/extras/AppVault/strings/strings_pt_BR.xml

**Comment by EduardoRGCM** [comment]
> Todos já estão traduzido aqui -> https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/blob/main/Brazilian-Portuguese/extras/AppVault/strings/strings_pt_BR.xml

Por qual motivo eles não estão aparecendo traduzidos? Existe alguma informação que eu possa repassar ao dev para corrigir a tradução?
Aquela outra dos modos de bateria que tinha que modificar alguma coisa no sistema eu reportei e foi corrigido, está traduzido agora.
Talvez sobre a tradução dos widgets seja algo semelhante?

**Comment by DiorgenesS** [comment]
Ele precisa sincronizar esse repo com o servidor que eles usam.
Se verificar o arquivo do servidor está desatualizado.
https://provider.xiaomi.eu/appvault/strings/strings_pt_BR.xml

**Comment by EduardoRGCM** [comment]
Obrigado, vou reportar ao dev.

**Comment by DiorgenesS** [comment]
@EduardoRGCM o player de musica, só encontrei as linhas hoje.
Já traduzir, pode ver aqui -> https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/commit/a7b9b4944ebcbc12d945756a7606684319c3dade, só que é preciso informar o dev para fazer o sync novamente com o servidor.

**Comment by EduardoRGCM** [comment]
@DiorgenesS Eu havia notado que os widgets estavam traduzidos, só não havia notado esse do player.
Obrigado! 
Vou entrar em contato com o Dev e falar com ele pra atualizar.
