### ISSUE TITLE
Widget de música sem tradução 

### ISSUE THREAD

**Issue by Luixgui** [RicardoGuariento/MIUI-XML-14-BRAZILIAN#23]
Os outros widgets estão traduzidos no App Vault, exceto o widget do aplicativo de música ![Screenshot_2023-09-25-10-06-56-010_com.miui.personalassistant.jpg](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/145996069/3af82c3d-36da-46ae-bfd8-e10e4ea36e5d)

**Comment by DiorgenesS** [comment]
Essa linha ainda não está disponível para tradução, caso eu encontre faço a tradução

**Comment by DiorgenesS** [comment]
Traduzido -> https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/commit/a7b9b4944ebcbc12d945756a7606684319c3dade
