### ISSUE TITLE
Mensagem de erro ao adicionar Widget

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/MIUI-XML-14-BRAZILIAN#24]
A mensagem de erro que aparece ao adicionar um widget com o app vault ativo não está traduzida
![Screenshot_2023-09-26-18-10-58-194_com.miui.personalassistant.jpg](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/f28eef46-8581-458c-99d8-147679ad2d8d)

https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/1beb1072-b113-40d5-aa6c-bdcba3627e74

**Comment by DiorgenesS** [comment]
@EduardoRGCM
Ambas já estavam traduzidas.
Linhas originais em inglês - > [View more](https://github.com/ingbrzy/Xiaomi.eu-MIUIv14-XML-Compare/blob/master/ingres/PersonalAssistant.apk/res/values/strings.xml#L717C1-L717C65) e [This widget isn't available yet....](https://github.com/ingbrzy/Xiaomi.eu-MIUIv14-XML-Compare/blob/master/ingres/PersonalAssistant.apk/res/values/strings.xml#L678C1-L678C139)

Linhas traduzidas: [aqui](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/blob/main/Brazilian-Portuguese/main/PersonalAssistant.apk/res/values-pt-rBR/strings.xml#L428C19-L428C53) e [aqui](pa_picker_detail_view_more)

**Comment by EduardoRGCM** [comment]
@DiorgenesS por qual motivo não está traduzido na ROM? O dev precisa de mudar alguma coisa?

**Comment by DiorgenesS** [comment]
Nao sei ao certo, deveria esta traduzido, pois essa tradução foi feita a muito tempo, em outro idioma está traduzido? Ex.: se mudar para espanhol, esse texto fica em espanhol?

**Comment by EduardoRGCM** [comment]
Mudei pra espanhol e continua em Inglês

![Screenshot_2023-09-26-19-17-42-302_com.miui.personalassistant.jpg](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/ce7a8064-d880-4d41-b782-376cec751e72)

**Comment by DiorgenesS** [comment]
Veja com o dev, realmente nao sei pq nao esta traduzido

**Comment by EduardoRGCM** [comment]
Já reportei ao dev, vou aguardar a resolução.
Obrigado
