### ISSUE TITLE
Digitalização de Documentos no app Scanner

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/MIUI-XML-14-BRAZILIAN#25]
Quando selecionado o modo Documentos no App Scanner, o modo selecionado não é traduzido.

![IMG_20230927_094633.jpg](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/19f87234-7ba9-45b6-990e-d3cb79b35932)

**Comment by DiorgenesS** [comment]
O meu está traduzido.
Versão do app. 14.0.3
![Screenshot_2023-09-27-10-28-22-622_com xiaomi scanner](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/16513009/443ac234-9089-4ae5-95da-730fbc9a2483)

**Comment by EduardoRGCM** [comment]
Realmente, apliquei uma fonte com menos espaçamento e percebi que é só questão da fonte padrão que não dá o espaçamento para aparecer a palavra inteira.
Obrigado! 

![Screenshot_2023-09-27-10-40-14-901_com.xiaomi.scanner.jpg](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/1ec34b18-023a-4392-8bad-79b5cc1d37c6)
