### ISSUE TITLE
Erro de tradução Mi Browser

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/MIUI-XML-14-BRAZILIAN#26]
![IMG_20230927_183526.jpg](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/3e162d7b-09f7-45d7-8cbd-716f1097696f)

**Comment by DiorgenesS** [comment]
Esse navegador é utilizado a versão global para a ROM, então ao meu ver não há necessidade de tradução de um app que já tem tradução. Então para esse app específico eu parei de traduzir a muito tempo.
