### ISSUE TITLE
Widget de atalho para as configurações 

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/MIUI-XML-14-BRAZILIAN#27]
Ao escolher um atalho para o widget de configurações a opção de configurações do botão de navegação não está traduzido.
Nem mesmo o widget está traduzido.
![Screenshot_2023-09-30-19-24-17-791_com.android.settings.jpg](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/2dc1910b-2223-42d2-bd3d-af636de6b405)

![Screenshot_2023-09-30-19-24-23-712_com.android.settings.jpg](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/acaefcb9-555a-4312-8062-7cadd8d095e2)

https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/8a65a58b-cc89-4f1b-9fd2-66f5979bceed

**Comment by DiorgenesS** [comment]
Procurei essa linha e não encontrei, estranho.

E percebi que a xiaomi removeu essa opção para ativar o assistente ao menos no meu dispositivo, agora só ativa através do botão de liga desliga.

Edit: mesmo com essa função do atalho ativa, não está acionando o assistente 

![Screenshot_2023-09-30-19-46-42-844_com miui miinput](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/16513009/5fe5b403-5f99-476d-82a9-b995184cbb1a)

**Comment by EduardoRGCM** [comment]
@DiorgenesS fiz o teste aqui no meu, e aqui ele ativa o assistente

https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/9ec4d829-1546-455c-ad0e-7d62cc456e19

**Comment by DiorgenesS** [comment]
Aí abrir o atalho por gestos, conforme a captura que coloquei anteriormente, aparece quantas opções para ativar o assistente no seu.

Em relação a tradução não encontrei essa linhas, me envia seu arquivo de Configurações.apk. vou analisar

**Comment by EduardoRGCM** [comment]
https://drive.google.com/drive/folders/1BVf7y9X4STnyS1eebXyUhvH77-ME2bOb?usp=sharing

Fiz o upload dos dois arquivos, não sei exatamente qual dos dois você vai precisar.

**Comment by DiorgenesS** [comment]
Analisei, e as linhas não estão presentes.
Mande a MiuiSystemUi.apk, o demais arquivos já pode remover do driver

**Comment by EduardoRGCM** [comment]
Não encontrei nenhum pacote com esse nome específico, extrai os que tinham systemui, verifique se é o que você precisa.

https://drive.google.com/drive/folders/1BVf7y9X4STnyS1eebXyUhvH77-ME2bOb?usp=sharing

**Comment by DiorgenesS** [comment]
não é nenhum desses. Nome do pacote: com.android.systemui

**Comment by EduardoRGCM** [comment]
Pronto, coloquei na pasta.
https://drive.google.com/drive/folders/1BVf7y9X4STnyS1eebXyUhvH77-ME2bOb?usp=sharing

**Comment by DiorgenesS** [comment]
Também não encontrei

**Comment by EduardoRGCM** [comment]
Pelo que eu percebi aqui, é no com.android.settings

Fiz o upload novamente https://drive.google.com/drive/folders/1BVf7y9X4STnyS1eebXyUhvH77-ME2bOb?usp=drive_link

https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/239f6242-de2f-468a-af3d-bcce88c63951

**Comment by DiorgenesS** [comment]
Sim é nas Configurações, porém não encontro essas strings em nenhum lugar

**Comment by EduardoRGCM** [comment]
O jeito é deixar como está, é uma função que acredito ser pouco usada.
