### ISSUE TITLE
Erro de tradução na seção Limpeza profunda 

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/MIUI-XML-14-BRAZILIAN#28]
![IMG_20231003_223419.jpg](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/b495cab4-f824-4ba0-bdd4-0521f0240f2d)

**Comment by DiorgenesS** [comment]
Foi traduzido a 2 semanas -> https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/commit/a0a87bea156b19dc2c70a1d78348f89e287966ea#diff-fcfad7f1b26e6470df5c4a9556aa77c016fa79837f634de6d2cba5e0606a01ffR287, mas ao verificar o apk da ultima rom lançada, a linha nao foi incluída, nao sei o motivo por nao ter sido

**Comment by EduardoRGCM** [comment]
![Screenshot_2023-10-17-10-47-39-909_com.miui.cleaner.jpg](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/20a48f6c-eedd-4755-882f-eae0d9357144)

Foi corrigido na última atualização
