### ISSUE TITLE
Mi11Ultra - Esporadicamente a Tela bloqueia pra sempre. (Só forçando o desligamento e o ligando novamente para utilizar o aparelho)

### ISSUE THREAD

**Issue by pradovinicius** [RicardoGuariento/MIUI-XML-14-BRAZILIAN#3]
Algumas vezes ao bloquear o Mi 11 Ultra ele não desbloqueia mais. A tela fica preta e nem a tela ambiente aparece mais. Tela traseira continua funcionando normalmente. Mas a tela principal aparentemente permanece bloqueada. O botão de desbloqueio não a ativa. Aconteceu umas 4 vezes depois que atualizei para MIUI 14 (todas as versões). Só forçando o desligamento e o ligando novamente para conseguir utilizar o aparelho.

**Comment by DiorgenesS** [comment]
Acredito que isso não seja causado pela tradução PT-BR, então você pode tentar buscar ajuda no fórum aonde baixou a ROM.
