### ISSUE TITLE
Nível de UV / App Clima 

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/MIUI-XML-14-BRAZILIAN#30]
![IMG_20231111_124647.jpg](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/d2534750-d147-4c46-bfa2-00efcc230624)

Os níveis de UV não estão traduzidos

**Comment by DiorgenesS** [comment]
Corrigido - > https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/commit/e0a62f9280f41bf13222e8c3b9825e4da8b6165d
