### ISSUE TITLE
Cálculo de IMC / App calculadora 

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/MIUI-XML-14-BRAZILIAN#31]
![Screenshot_2023-11-13-14-45-00-212_com.miui.calculator.jpg](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/04f3cc85-9423-4e91-b299-7c7443718076)

**Comment by DiorgenesS** [comment]
Corrigido - >https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/commit/e0a62f9280f41bf13222e8c3b9825e4da8b6165d
