### ISSUE TITLE
Google Pay parou de funcionar na MIUI 14.0.14

### ISSUE THREAD

**Issue by Op1rus** [RicardoGuariento/MIUI-XML-14-BRAZILIAN#32]
desde a versão da MIUI 14.0.13 o Google Pay parou de funcionar logo após atualização automática do app Google Pay. já atualizei para MIUI 14.0.14 e continua a mensagem que meu smartphone não atende aos padrões de segurança por conta do root. Alguém tem uma solução?

**Comment by EduardoRGCM** [comment]
Eu acredito que aqui não seja o local adequado para conseguir ajuda, dê uma olhada no fórum da xiaomi.eu, acredito que já tenha essa solução, é um problema com o Play Integrity.
