### ISSUE TITLE
erro de tradução.

### ISSUE THREAD

**Issue by tavareswillian1993** [RicardoGuariento/MIUI-XML-14-BRAZILIAN#6]
o pop up de localização aproximada está com a tradução dos botões invertidos.

"não" significa "manter ligado" e "sim" significa "desligar".

**codigo atual:**
```
<string name="keep_blur_location">No</string>
<string name="stop_blur_location">Yes</string>
```

**correção:**
```
<string name="keep_blur_location">Manter ligado</string>
<string name="stop_blur_location">Desligar</string>
```

**Comment by DiorgenesS** [comment]
https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/commit/3f5a86619c3e4c2a27ef532915243ab456b5ce54

Fixed
