### ISSUE TITLE
Control Notification Sounds

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/MIUI-XML-14-BRAZILIAN#8]
In sounds and haptic feedback, in the "Sounds" tab, the **Control Notification Sounds** option is in English, as well as the description of the feature.

**Comment by DiorgenesS** [comment]
@EduardoRGCM poderia fornecer uma captura de tela?

**Comment by EduardoRGCM** [comment]
![Screenshot_2023-08-21-09-11-31-816_com.android.settings.jpg](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/b9b0821f-fb1c-4726-9e7c-8217e0dfce75)

@DiorgenesS

**Comment by DiorgenesS** [comment]
@EduardoRGCM Consegue disponibilizar o Settings.apk? Pois acredito que voce esteja usando a versão estavel, pois nao localizei essas strings na versão dev

**Comment by EduardoRGCM** [comment]
> @EduardoRGCM Consegue disponibilizar o Settings.apk? Pois acredito que voce esteja usando a versão estavel, pois nao localizei essas strings na versão dev

OK, fiz o upload no Gdrive já que não deu pra enviar anexado aqui. Não sei se serve de alguma coisa, mas na Miui Global que eu estava usando, já estava com tradução. 
Fiz o upload de dois apks, não tive certeza de qual era exatamente.

https://drive.google.com/drive/folders/1MkB00VN_UAHqqFfh9g1psVeeh__zN8ox?usp=drive_link

**Comment by DiorgenesS** [comment]
@EduardoRGCM resolvido, https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/commit/07c19e73c8f13cca8afb185691201546fdfef062, estará disponível na próxima rom estavel e dev, se quiser pode remover os arquivos do drive.
