### ISSUE TITLE
Google Photos Backup on Gallery 

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/MIUI-XML-14-BRAZILIAN#9]
![Screenshot_2023-08-21-15-05-08-285_com.miui.gallery.jpg](https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/assets/91606482/7f349d93-c712-45a0-bbd1-07ada6eccd57)

O título, bem como a descrição da opção de backup do Google Fotos não estão traduzidos.

**Comment by DiorgenesS** [comment]
Feito-> https://github.com/RicardoGuariento/MIUI-XML-14-BRAZILIAN/commit/035ee18bc1455e1b39d71dcbd36b3209a3a269ad
